sudo: false
language: c

addons:
  apt:
    packages:
    - device-tree-compiler

before_install:
    - export CXXFLAGS="$CXXFLAGS -fPIC"

install:
    - ./scripts/feeds update -a
    - ./scripts/feeds install -a
    - cat target/linux/pistachio/creator-platform-default.config > ./.config

script:
    - make defconfig
    - ./.travis.sh
